version: 2

jobs:

  build-python36:
    docker:
      - image: python:3.6.0
    steps:
      - checkout
      - run: pip install .
      - run: make test

workflows:
  version: 2
  build:
    jobs:
      - build-python36
